### ISSUE TITLE
 Cannot bind parameter 'Headers'. Cannot convert the "Content-Type: application/ld+json" value of type "System.String" to type "System.Collections.IDictionary".

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDES-E2E-testing#121]
Hello VSDS team:
I am following the procedure described at: [https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/ldes-server-simulator] for Node.js set up.
I tried to **_upload an LDES fragment from the (Bash) command line using curl:_**
Step:
`-  **curl -X POST http://localhost:8080/ldes -H "Content-Type: application/ld+json" -d "@sample.jsonld"**`
![image](https://user-images.githubusercontent.com/15314807/209357060-48f62cc5-c2ff-4e11-8d3c-14777dee6bd3.png)

Result:
I got the error:

```
Invoke-WebRequest : Cannot bind parameter 'Headers'. Cannot convert the "Content-Type: application/ld+json" value of
type "System.String" to type "System.Collections.IDictionary".
At line:1 char:44
+ ... ://localhost:8080/ldes -H "Content-Type: application/ld+json" -d "@sa ...
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

![image](https://user-images.githubusercontent.com/15314807/209357119-7140a8bd-f797-4774-aea1-a0e9d990bd7e.png)

Please help me with it
Thanks

**Comment by rorlic** [comment]
Hi, looking at your error log I see that you run the command in a PowerShell environment.

The ["curl" command in PS](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.3) is **not compatible** with the [real curl command](https://curl.se/).

Please make sure you use a [bash command environment ](https://git-scm.com/download/win) to run the [curl command](https://curl.se/windows/).
