### ISSUE TITLE
Typo at https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/use-cases/gtfs-and-rt/1.ingest-ldes

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDES-E2E-testing#127]
Hello VSDS Team,

I hope you are doing well.

On the page : https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/use-cases/gtfs-and-rt/1.ingest-ldes

The sentence:  
~ a personal file (e.g. user.env) and fill in the mandatory arguments or, if available, append the specific  `env.<gtfs-use-case> ` file to your personal file.

According to the context, I think it should be `<gtfs-use-case>.env` instead of `env.<gtfs-use-case>`

Please correct me if I am wrong.

Thanks a lot

**Comment by rorlic** [comment]
Hi, Xueying, you are absolutely right. At some point we changed the naming of the env files to allow for syntax coloring and therefore easier editing. Thanks for catching this.

I have fixes the docs and other files for this and other use cases (including the client sink). Please review and please keep posting any issues you bump into. Highly appreciated!
