### ISSUE TITLE
Read me demo url issue: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/use-cases/gtfs-and-rt/2.geo-fragmentation

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDES-E2E-testing#131]
Hello VSDS team.

I see some differences between the default configuration file ([docker-compose.yml](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/e2e-test/use-cases/gtfs-and-rt/2.geo-fragmentation/docker-compose.yml)) and the demo description ([README.md](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/e2e-test/use-cases/gtfs-and-rt/2.geo-fragmentation/README.md)).

- ([docker-compose.yml](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/e2e-test/use-cases/gtfs-and-rt/2.geo-fragmentation/docker-compose.yml))  contains: 

` VIEWS_0_NAME=mobility-hindrances-by-location`

- ([README.md](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/e2e-test/use-cases/gtfs-and-rt/2.geo-fragmentation/README.md)) describes:

 `curl http://localhost:8080/mobility-hindrances/by-location?tile=0/0/0`         =>  (Current Error, **Not a valid URL**. When step by step follow the demo description)

- The URL to root fragment I think it should be:

`http://localhost:8080/mobility-hindrances/mobility-hindrances-by-location?tile=0/0/0 `

Please feel correct me if I am wrong

This issue (Similar URL issue) also applies to all demos with the GIPOD data in the folder: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/use-cases/gtfs-and-rt. For the URL of fragment by time as well.

Thanks

**Comment by rorlic** [comment]
Hi Xueying, nice catch! I'll fix all the docker-compose.yml files. Initially, we did not include the LDES name in the URL, so the view name also contained the collection name. After implementing the correct URL naming, I adapted the documentation and the docker-compose files but clearly missed a few. I'll fix right away.

**Comment by xdxxxdx** [comment]
Hello @rorlic ,

Please also see the Demo for the data of Internet of Water: 
https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/use-cases/iow/3.ngsi-v2-to-ldes

In the ([Docker-compose.yml](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/e4686046fca7df4f220f0903d6d4d3b88ab7e48d/e2e-test/use-cases/iow/3.ngsi-v2-to-ldes/docker-compose.yml)). 

`VIEWS_0_NAME=devices-by-time`
`VIEWS_0_NAME=device-models-by-time`
`VIEWS_0_NAME=water-quality-observations-by-time`

At ([Read me] https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/use-cases/iow/3.ngsi-v2-to-ldes)

The Fragments root URL are:

curl -H "Accept: application/ld+json" http://localhost:8071/devices/by-time
curl -H "Accept: application/ld+json" http://localhost:8072/device-models/by-time
curl -H "Accept: application/ld+json" http://localhost:8073/water-quality-observations/by-time


Please also modify the URL accordingly based for the data of IoW, 

Thanks

**Comment by rorlic** [comment]
Thank you. I already noticed and have a fix ready (branch related to #135). I am currently verifying all E2E tests.
