### ISSUE TITLE
InValid processor, IoW 1.ngsi-v2-to-ld use-case : https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/e2e-test/use-cases/iow/1.ngsi-v2-to-ld/nifi-workflow.json

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDES-E2E-testing#147]
Hello VSDS team, I detected a small issue about the file:  [nifi-workflow.json](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/e2e-test/use-cases/iow/1.ngsi-v2-to-ld/nifi-workflow.json)

**Prerequisites:**

LDES-workbench-nifi:
Docker image tag: [20230116t113945](https://github.com/Informatievlaanderen/VSDS-LDESWorkbench-NiFi/pkgs/container/ldes-workbench-nifi/59271243?tag=20230116t113945)

LDES-workbench-nifi is running at the port 8443 https://localhost:8443/nifi/, and user is logged in

**Scenario:**
Upload [nifi-workflow.json](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/e2e-test/use-cases/iow/1.ngsi-v2-to-ld/nifi-workflow.json) (with latest commit: 86536dc6ea35c2add36593bb533a338a38407dcf) to the NIFI-workbench

**Current result:**
CreateVersionObjectProcessor is inValid.
Please see: 
![image](https://user-images.githubusercontent.com/15314807/214149886-b19bf081-b19c-4db6-9012-33b231f06fc6.png)

same issue also applies to https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/e2e-test/use-cases/iow/3.ngsi-v2-to-ldes/nifi-workflow.json

**Expected result:**
No processor is inValid

P.s:
The previous version: [nifi-workflow.json](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/e2e-test/use-cases/iow/1.ngsi-v2-to-ld/nifi-workflow.json), with the commit (74a12fde88610c4fc37d70dfddfda154ae5072d5) has NO issue.

Thanks
XD

**Comment by rorlic** [comment]
@xdxxxdx fixed, please verify. Thank you!

**Comment by zargha** [comment]
Thanks!

**Comment by xdxxxdx** [comment]
Validated on the [VSDS-LDESWorkbench-NiFi](https://github.com/Informatievlaanderen/VSDS-LDESWorkbench-NiFi) docker image:  [20230127T135852](https://github.com/Informatievlaanderen/VSDS-LDESWorkbench-NiFi/pkgs/container/ldes-workbench-nifi/59271243?tag=20230127T135852)
