### ISSUE TITLE
host not found in nginx

### ISSUE THREAD

**Issue by zargha** [Informatievlaanderen/VSDS-LDES-E2E-testing#149]
While running [e2e-test/demos/ldes-server-caching](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/demos/ldes-server-caching), the nginx docker container fails to run with the error log:

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/01/25 12:42:21 [emerg] 1#1: host not found in upstream "ldes-server" in /etc/nginx/conf.d/fwd-ldes-server.conf:9
nginx: [emerg] host not found in upstream "ldes-server" in /etc/nginx/conf.d/fwd-ldes-server.conf:9

```

System:
Ubuntu 20.04
Docker version 20.10.23
Docker Compose version v2.12.2

**Comment by rorlic** [comment]
Must be something related to your local (docker?) environment. You should get something like:
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/01/26 09:39:15 [notice] 1#1: using the "epoll" event method
2023/01/26 09:39:15 [notice] 1#1: nginx/1.23.3
2023/01/26 09:39:15 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2023/01/26 09:39:15 [notice] 1#1: OS: Linux 5.15.0-58-generic
2023/01/26 09:39:15 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2023/01/26 09:39:15 [notice] 1#1: start worker processes
2023/01/26 09:39:15 [notice] 1#1: start worker process 30
2023/01/26 09:39:15 [notice] 1#1: start worker process 31
2023/01/26 09:39:15 [notice] 1#1: start worker process 32
2023/01/26 09:39:15 [notice] 1#1: start worker process 33
2023/01/26 09:39:15 [notice] 1#1: start cache manager process 34
2023/01/26 09:39:15 [notice] 1#1: start cache loader process 35
2023/01/26 09:40:16 [notice] 35#35: http file cache: /var/cache/nginx/static-cache 0.000M, bsize: 4096
2023/01/26 09:40:16 [notice] 1#1: signal 17 (SIGCHLD) received from 35
2023/01/26 09:40:16 [notice] 1#1: cache loader process 35 exited with code 0
2023/01/26 09:40:16 [notice] 1#1: signal 29 (SIGIO) received
```

Try deleting your networks, purging old images, etc.

**Comment by rorlic** [comment]
@zargha can you check the Docker logs for the LDES server? Is it running? Please attach to the nginx container and try pinging `ldes-server`.

**Comment by xdxxxdx** [comment]
Hello @rorlic , 
We retried this case with the same setup and the new docker image tag for sprint 19.

- NGINX: 1.23.3-alpine
- ldes-server: 20230131t0819


System:

- Ubuntu 20.04
- Docker version 20.10.23
- Docker Compose version v2.12.2

The issue stays.
And you are right, after launching the docker composed containers. From the NGINX docker console, the ip of ldes-server cannot be resolved. 
We tried delete all docker networks/all containers/ all images.

This issue doesn't occurs on docker running on the WSL2 + Windows 10 set up

Thanks
XD

**Comment by zargha** [comment]
@rorlic @xdxxxdx i had a look at this issue. In the nginx.conf, there is parameter         proxy_pass http://ldes-server:8080;
i changed it to http://localhost:8080, and nginx started running.
On my Ubuntu, apparently it couldnt reach http://ldes-server:8080.

I will close this issue, but i think the best would be to use http://localhost:8080 in the nginx.conf since its running as localhost to avoid any dns issues.

**Comment by rorlic** [comment]
@zargha I a bit confused, by configuring it like that the nginx will proxy to itself and you will get a `502 Bad Gateway` response

**Comment by rorlic** [comment]
try the following to clean up your environment:
```bash
docker compose down
docker network rm setup-caching_network
```

now, retry the `docker compose up` and verify that the nginx now starts correctly

**Comment by rorlic** [comment]
@zargha @xdxxxdx if the above does not work, can you update your docker version and compose version to the latest?
- `Docker version 23.0.1, build a5ee5b1`
- `Docker Compose version v2.16.0` (comes with the above docker version)

BTW: I run on Linux Mint 21.1 which is derived from Ubuntu 22.04

**Comment by zargha** [comment]
> @zargha I a bit confused, by configuring it like that the nginx will proxy to itself and you will get a `502 Bad Gateway` response

you are right @rorlic. indeed this is the case!

**Comment by zargha** [comment]
> @zargha @xdxxxdx if the above does not work, can you update your docker version and compose version to the latest?
> 
> * `Docker version 23.0.1, build a5ee5b1`
> * `Docker Compose version v2.16.0` (comes with the above docker version)
> 
> BTW: I run on Linux Mint 21.1 which is derived from Ubuntu 22.04

yes, i will check with the latest vesions.

**Comment by zargha** [comment]
i tested it with `Docker Compose version v2.15.1` and nginx is running. I will close this issue.
