### ISSUE TITLE
The output json file is not identical with the expected json file : https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/use-cases/iow/1.ngsi-v2-to-ld

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDES-E2E-testing#156]
Hello VSDS team,

The test is on : [VSDS-LDESWorkbench-NiFi](https://github.com/Informatievlaanderen/VSDS-LDESWorkbench-NiFi) : [20230127T135852](https://github.com/Informatievlaanderen/VSDS-LDESWorkbench-NiFi/pkgs/container/ldes-workbench-nifi/59271243?tag=20230127T135852)

GitHub commit tag: [aa3a564526f238993838c8e2a799b6e3cac2f742](https://github.com/Informatievlaanderen/VSDS-LDESWorkbench-NiFi/commit/aa3a564526f238993838c8e2a799b6e3cac2f742)

Docker image tag: [20230127T135852](https://github.com/Informatievlaanderen/VSDS-LDESWorkbench-NiFi/pkgs/container/ldes-workbench-nifi/59271243?tag=20230127T135852)

With the fix https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/commit/86536dc6ea35c2add36593bb533a338a38407dcf

I see the processor is changed from: 

`CreateVersionObjectProcessor` to `be.vlaanderen.informatievlaanderen.ldes.processors.NgsiV2ToLdTranslatorProcessor`

also 
`"CORE_CONTEXT": "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld", `
is changed to:
`"CORE_CONTEXT": "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.3.jsonld".
`

For current case, If I follow step by step of: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/use-cases/iow/1.ngsi-v2-to-ld

Till the step : `py ./normalized2LD.py ./data/input/WaterQualityObserved.json ./data/expected/WaterQualityObserved.json https://json-ld.org/test-suite/context.jsonld`

I got the the expected result with the different context with the output result.
The output result is with the following context:

`  "@context" : [ "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.3.jsonld" ],`

The expected result with the following context:
```

   "  "@context": [
        "https://json-ld.org/test-suite/context.jsonld",
        "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
    ],
```
I think here might need some small modifications.

Thanks, and regards 
XD

**Comment by rorlic** [comment]
@xdxxxdx we have removed this test because it was not an end-to-end test but rather a component test. So, I guess this ticket has been obsoleted. Can you please close it?
