### ISSUE TITLE
Actual Caching using NGNIX proxy doesn't work.

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDES-E2E-testing#158]
Hello @rorlic , VSDS team, 
I am resting the actual caching mechanism, I see the following issue.

**Prerequisites:**
- Follow the step by step demo by : https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/demos/ldes-server-caching.

The following docker images are running:
-    ghcr.io/informatievlaanderen/ldes-server : 20230131t0819 
-    nginx:1.23.3-alpine 

**Scenario:**
sent `"curl -i http://localhost:8080/mobility-hindrances/by-time "` first time

**Current result:** == **Expected result**
```
HTTP/1.1 200
Server: nginx/1.23.3
Date: Mon, 06 Feb 2023 16:09:58 GMT
Content-Type: text/turtle
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Cache-Control: public,max-age=60
Content-Disposition: inline
ETag: "23403a5fb008a59d353d2e08156b3c7a6dba93343b580383a3ad7e47f0589d5d"
X-Cache-Status: HIT

@prefix ldes:                <https://w3id.org/ldes#> .
@prefix mobility-hindrances: <http://localhost:8080/mobility-hindrances/> .
@prefix tree:                <https://w3id.org/tree#> .

mobility-hindrances:by-time
        a              tree:Node ;
        tree:relation  [ a          tree:Relation ;
                         tree:node  <http://localhost:8080/mobility-hindrances/by-time?generatedAtTime=2023-02-01T12:32:20.283Z>
                       ] .

<http://localhost:8080/mobility-hindrances>
        a          ldes:EventStream ;
        tree:view  mobility-hindrances:by-time .
```

**Scenario:**
Re-sent `"curl -I http://localhost:8080/mobility-hindrances/by-time"` in 60m

**Current result:** 
```
HTTP/1.1 200
Server: nginx/1.23.3
Date: Mon, 06 Feb 2023 16:12:27 GMT
Content-Type: text/turtle
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Cache-Control: public,max-age=60
Content-Disposition: inline
ETag: "23403a5fb008a59d353d2e08156b3c7a6dba93343b580383a3ad7e47f0589d5d"
X-Cache-Status: EXPIRED

@prefix ldes:                <https://w3id.org/ldes#> .
@prefix mobility-hindrances: <http://localhost:8080/mobility-hindrances/> .
@prefix tree:                <https://w3id.org/tree#> .

mobility-hindrances:by-time
        a              tree:Node ;
        tree:relation  [ a          tree:Relation ;
                         tree:node  <http://localhost:8080/mobility-hindrances/by-time?generatedAtTime=2023-02-01T12:32:20.283Z>
                       ] .

<http://localhost:8080/mobility-hindrances>
        a          ldes:EventStream ;
        tree:view  mobility-hindrances:by-time .
```
**_As the second ping to NGNIX is less than 60 m, I think here should be `X-Cache-Status` should be  `HIT?`_**

Please correct me I am wrong
Thanks
Regards
XD

**Comment by xdxxxdx** [comment]
Hello @rorlic,

As discussed, this case is more a documentation issue.
For the caching mechanism, maybe it is better to explain:

- For mutable resource: 
The actual caching takes the **_min(MAX_AGE (setting for the LDES Server), proxy_cache_valid (setting in ngix.conf))._**

- For immutable resource:
The actual caching takes the **_min (MAX_AGE_IMMUTABL (setting for the LDES Server), proxy_cache_valid  (setting for the ldes server))_**

Also there are three status for` X-Cache-Status` : `MISS`, `EXPIRED`,`HIT`

Please feel free to correct me
Thanks, and regards
Xueying

**Comment by rorlic** [comment]
FYI: the test has been renamed and the actual fix can now be found here:
https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/tests/019.server-supports-cacheability#verify-actual-caching

**Comment by xdxxxdx** [comment]
Close and validated with the E2E tag: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/commit/bb3cd5fcc2212e359f5e91732258027e7dc3a7a0
