### ISSUE TITLE
The referred view.ttl file is missing, https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/demos/ldes-server-caching, 

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDES-E2E-testing#159]
Hello,

On the page : https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/demos/ldes-server-caching
![image](https://user-images.githubusercontent.com/15314807/217037307-588266c5-366d-47f0-a774-6197af25e8ac.png)
The referred` view.ttl` by the linked tex `turtle file` is missing.
![image](https://user-images.githubusercontent.com/15314807/217037541-76d0f250-252b-4149-b034-3c17a0c64c27.png)

Thanks
XD

**Comment by rorlic** [comment]
Hi, I will improve the documentation to make it more clear that you need to run the bash commands as indicated in the [README.md](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/demos/ldes-server-caching#verify-nginx-compression-setup) file in the directory where the README.md file is located. If you do so, the `gzip -d view.ttl.gz` will result in the 'missing file' `view.ttl`. Can you please try this and close this issue?

**Comment by xdxxxdx** [comment]
Hello @rorlic ,
It works for me, thanks!
