### ISSUE TITLE
ldes-client-persistence is not working properly:  https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/demos/ldes-client-persistence

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDES-E2E-testing#161]
Hello, 

I notice the following issue in sprint 19:

**Prerequisite:**

- The docker image:  
       - ghcr.io/informatievlaanderen/ldes-client-sink:20230130t0856
       - ghcr.io/informatievlaanderen/ldes-server-simulator:20230130t0856
       - ghcr.io/informatievlaanderen/ldes-workbench-nifi :20230127T135852 
       
- Follow the step by step example showed on : https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/demos/ldes-client-persistence
- Keep the default[ NIFI flow](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/e2e-test/demos/ldes-client-persistence/flows/nifi-workflow.json) setting:   "DATA_SOURCE_URL": "http://ldes-server-simulator/api/v1/ldes/mobility-hindrances?generatedAtTime=2022-04-19T12:12:49.47Z"

**Scenario:**

- Start Nifi flow => wait for 250 member synchronized
- Stop the Nifi flow
- Restart the Nifi flow

**Current result:**
the root fragment ("http://ldes-server-simulator/api/v1/ldes/mobility-hindrances?generatedAtTime=2022-04-19T12:12:49.47Z)
![image](https://user-images.githubusercontent.com/15314807/217290217-ec4156c8-14b5-4314-9ab5-6cb1ac5ac8c9.png)
has been requested more than 1 time

**Expected result:**
No matter where in the LDES you halted the NiFi processor, none of the requested fragments should have a count higher than 1.

**Investigation**

If I set as described in : 
https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/demos/ldes-client-persistence 

`the LdesClient component property Datasource url should be http://ldes-server-simulator/api/v1/ldes/mobility-hindrances`

From my idea, to request all the LDES stream, the follow alias needs to be created:

`
{
    "original": "http://ldes-server-simulator/api/v1/ldes/mobility-hindrances?generatedAtTime=2022-04-19T12:12:49.47Z",
    "alias": "http://ldes-server-simulator/api/v1/ldes/mobility-hindrances"
}`

With bash command `curl -X POST http://localhost:9011/alias -H "Content-Type: application/json" -d '@create-alias.json'`

In this situation. the root fragment (http://localhost:9011/api/v1/ldes/mobility-hindrances?generatedAtTime=2022-04-19T12:12:49.47Z) also been requested more than 1 time.

Please feel free to correct me If I am wrong
Thanks 
Best regards
XD

**Comment by rorlic** [comment]
This test has been changed to use the LDIO workbench instead of a NiFi workbench. We will review and update the documentation. However, the LDES client was fixed this sprint to request fragments only once. Because of redirects (HTTP 302) and because the LDES client needs to determine which view to follow, the first URL (typically the LDES) may be queried twice. We will update the documentation to include this information.

**Comment by rorlic** [comment]
FYI: the test has been renamed and can now be found at:
https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/demos/020.client-pause-and-resume

**Comment by xdxxxdx** [comment]
Wait for the fix of:
https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/issues/175 
https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/issues/152
To revalidate current case.

**Comment by xdxxxdx** [comment]
Validated on ghcr.io/informatievlaanderen/ldi-orchestrator:20230508T085639
with E2E tag: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/commit/937e069594828f84154032ebb05485323626b813
