### ISSUE TITLE
Update the cypress automation testing feature to use new docker images of LDES NIFI (ldi-workbench-nifi)

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDES-E2E-testing#209]
Hello Team,

The Github commit: VSDS_LDES_E2E_testing: 6d61fc7d64a900963316aea1f099938a5c45726f

I see the automation testing which is still using the older docker image LDES-workbench-nifi
![image](https://user-images.githubusercontent.com/15314807/226466849-f42bde21-fcac-4d83-a4fb-3d078a2f439e.png)
As the repositories are modified.
I think for caching the changes, the automation test features also needs to be modified to use: 
Which needs to be modified to: [ldi-workbench-nifi](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/pkgs/container/ldi-workbench-nifi)

Thanks
XD

**Comment by rorlic** [comment]
All tests have been changed to use LDIO as the preferred workbench.

Some tests explicitly need to use a NiFi workbench. For these, we now use the `ldi-workbench-nifi`.

Some (upgrade) tests still require the old `ldes-workbench-nifi` image. Obviously, we have not changed these.

**Comment by xdxxxdx** [comment]
Will retest the case once get the new tags and close it accordingly

**Comment by xdxxxdx** [comment]
Hello @rorlic ,

Please have look at: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/tests/012.server-provide-basic-retention.
The readme is still pointing to use NIFI solution. But no json workflow provided.

Thanks

**Comment by rorlic** [comment]
Hi, nice catch, thanks! I see some additional issues (missing image, use of mongo compass, etc.) Will fix asap.

**Comment by rorlic** [comment]
Fixed.
Please verify and close ticket.

**Comment by rorlic** [comment]
added the NiFi test
https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/demos/031.nifi-workbench-components

**Comment by xdxxxdx** [comment]
Hello @rorlic ,

Please also update the url used in https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/demos/023.nifi-workbench-upgrade.
`curl http://localhost:8080/devices-by-time` is not a valid one (Not changed for sprint 26)**

Thanks
