### ISSUE TITLE
E2E Cypress automation error:: Stderr: '.' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDES-E2E-testing#298]
**Prerequisites:**
Commit tage of E2E: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/commit/86851d8754928b27a7b51795b3c2884d3359043c
Cypress in installed on the windows  (binary version)
ldes/ldes-server:1.0.0-SNAPSHOT

**Scenario:**
Under the directory: PS C:\VSDS repository\VSDS-LDES-E2E-testing> using PowerShell  Run: `npm test -- -e tags="@test-002"` to run the second

**Current result:**
     CypressError: `cy.exec('cd tests/002.server-ingest-small-ldes/config && ./seed.sh')` failed because the command exited with a non-zero code.   
Please see:
![image](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/assets/15314807/767ee49a-2789-491d-b8f7-9a64e31c3670)
![image](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/assets/15314807/8188fbaf-5743-4fa1-b777-b8c5bce1d50a)

**P.S.**

This issue occurs to all tests need a POST request to configure the Server.

**Comment by rorlic** [comment]
This is (as usual) a windows issue: to separate commands `cmd.exe` uses `&&` or `&` while `powershell` uses `;`.
I cannot make this work for all shells on windows, so I will have to create a workaround ensuring no 2 commands are needed within the shell exec call.

**Comment by rorlic** [comment]
CORRECTION: PowerShell will never work due to its incompatible curl implementation. Cmd.exe will not work as it does not know how to execute a bash shell script.

Please use a Git bash to launch the automatic tests.

**Comment by rorlic** [comment]
The root cause of the problem is use of cypress.exec within the automatic tests. I have reworked the automation code to minimize the use of cy.exec by using as much as possible cypress alternatives such as cy.request. This should minimize the risk of incompatibility of the different shells.

Please retest with the latest test automation.

**Comment by xdxxxdx** [comment]
Tested with Gitbash with  Windows 11+WSL2.
Works perfectly
 7759a0450676cbc35f51567bbc58cdfbf6bf9c4a
