### ISSUE TITLE
Please also modify the https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/demos/031.nifi-workbench-components to the new LDES Server configuration

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDES-E2E-testing#309]
Hello [@rorlic](https://github.com/rorlic) ,
Please also have a look at this test case: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/demos/031.nifi-workbench-components
Currently, it is not updated to the newest configuration, please also modify it accordingly.
Thanks

**Comment by rorlic** [comment]
Nice catch!
I have indeed not fixed the tests under /demos ...
