### ISSUE TITLE
Please add an E2E test to cover LDIO RML Adapter

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDES-E2E-testing#313]
As there is no example in the doc.
Please add an E2E for this adapter to demonstrate how it works.

**Comment by Yalz** [comment]
Hi @xdxxxdx ,

I'm afraid there might be a misunderstanding to the purpose for this repository. 
The E2E test repo serves as a validation step that combines the docker deliverables from the LDES Server and LDI, not as an example library.

Regarding documentation on the RML mapper, there is an example available at https://informatievlaanderen.github.io/VSDS-Linked-Data-Interactions/ldio/examples/ex2-scrape-api
