### ISSUE TITLE
Sprint 31: Cypress auto test fails with error: 'sh' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDES-E2E-testing#331]
E2E repo tag: fe7119f9174c38fbc62ab0f0f0fe04d758b2480b
[ldes/ldes-server:1.3.0-SNAPSHOT](https://hub.docker.com/r/ldes/ldes-server/tags)
[ldes/ldi-workbench-nifi:1.3.0-SNAPSHOT](https://hub.docker.com/r/ldes/ldi-workbench-nifi/tags) 
[ldes/ldi-orchestrator:1.3.0-SNAPSHOT](https://hub.docker.com/r/ldes/ldi-orchestrator/tags)

**Scenario:**
Run `npm run test` under the directory

**Current result:**
All tests related to LDES Server failed with error:  'sh' is not recognized as an internal or external command, 
on  Powershell Gitbash or Ubuntu environment (WSL + Windows 11)

![image](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/assets/15314807/c9fcde17-ace9-47a1-bc20-42832bb5ac17)
Results: 
[Results.zip](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/files/12144899/Results.zip)

**Comment by rorlic** [comment]
can you run the following in the same location as where you ran `npm run test`:
```bash
which sh
```
and post the result here?

**Comment by xdxxxdx** [comment]
Hello @rorlic .
With the tag: 8b116de5e53f392fc2342f9fc3f054400cabd3c4,  There is no issue with the cypress run.

- Accordingly to, there is a fix at 20 July: 8b116de5e53f392fc2342f9fc3f054400cabd3c4 (working version)
- also the fix at 21 July: d27d175dc3b793b1055b98acc8f1c48626e0adaf (not working version)

I Was thinking both of them are supposed to be used for the testing of Sprint 31.
 (As discussed there is no change during the sprint, only for the hotfix)

The modification of the configuration brought by d27d175dc3b793b1055b98acc8f1c48626e0adaf led to this issue.

Thanks
Xueying
