### ISSUE TITLE
NiFi workflow re-start instructions

### ISSUE THREAD

**Issue by zargha** [Informatievlaanderen/VSDS-LDES-E2E-testing#34]
Extend README.md for NiFi workflow restart instructions for e2e test [20220705.demo1](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/20220705.demo1)

**Comment by rorlic** [comment]
The docs have been rewritten and restart instructions have been incorporated, see [GIPOD use case test 4.time-fragment-ldes](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/use-cases/gipod/4.time-fragment-ldes/README.md#restart-containers-between-the-scenarios)

**Comment by zargha** [comment]
Reviewed! I will closed this issue.
