### ISSUE TITLE
Update README for 20220705.demo1

### ISSUE THREAD

**Issue by zargha** [Informatievlaanderen/VSDS-LDES-E2E-testing#35]
#### The Problem

In the [README](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/feature/VSDSPUB-62-e2e-test/e2e-test/20220705.demo1#readme) of [20220705.demo1](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/feature/VSDSPUB-62-e2e-test/e2e-test/20220705.demo1#demo-1---july-5th-2022), terms such as `tree:relation`, `GreaterThanRelation` and `LessThanRelation` are used which couldn't be found in the response body when requesting LDES Server at http://localhost:8080/mobility-hindrances 

Instead these are found: `tree#relation`, `tree:GreaterThanOrEqualToRelation`, `tree:LessThanOrEqualToRelation`

**Comment by WLefever-Cegeka** [comment]
Hi @zargha,

I updated the README.md in the open PR #30.
