### ISSUE TITLE
Update the test https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/tests/021.server-upgrade for new upgrade mechanism

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDES-E2E-testing#378]
As the new upgrade mechanism explained by @WLefever-Cegeka. https://vsdscore.slack.com/archives/C03F58Z6PDF/p1692303282064809
I propose that updating E2E 021 https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/tests/021.server-upgrade to support this new mechanism.

**Comment by Yalz** [comment]
Slack message is no longer visible
