### ISSUE TITLE
Introduce new E2E test for the compaction mechanism 

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDES-E2E-testing#380]
With the fix of https://vlaamseoverheid.atlassian.net/browse/VSDSPUB-892 (Sprint 35)
it might be good to have an E2E combine LDES Server and LDES Client to

- Verify the compaction mechanism works also on the Server side.
- Verify the compacted Stream can be consumed by the LDES Client.

**Comment by Yalz** [comment]
Hi @xdxxxdx ,
We already have an IT that checks on these paths.
An e2e test would do the same, which does not bring any extra value to create a dedicated E2e
