### ISSUE TITLE
Please delete the github subtask with no test

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDES-E2E-testing#389]
After the integration test, lots of E2E tests are eliminated from the folder tests.
In correspondent to this change, the sub-job (task) of the GitHub action which is pointing to these deleted test should be removed.

e.g.
<img width="827" alt="image" src="https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/assets/15314807/e621e390-650f-4a46-b2f9-a8e6557b7316">

Thanks

**Comment by rorlic** [comment]
Done.
