### ISSUE TITLE
The repository is missing a .gitignore file at root level

### ISSUE THREAD

**Issue by Krieke** [Informatievlaanderen/VSDS-LDES-E2E-testing#39]
The repository is missing a .gitignore file.

**Comment by Yalz** [comment]
Hi Daniel, this repo does in fact have multiple .gitignore files.
Since this repo can be considered a hub for the tools (simulator & sink + e2e tests + e2e demos) with each individual gitignore files

**Comment by Krieke** [comment]
@Yalz Indeed, my remark was not clear enough. To add a .gitignore at root level. I notice each time when checking this repo that for example .idea are added to the untracked files.  => So add a .gitignore at root level
