### ISSUE TITLE
Invalid - CreateVersionObjectProcessor 1.9.0-SNAPSHOT

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDES-E2E-testing#395]
**Versions**
- [ldes/ldi-workbench-nifi:1.9.0-SNAPSHOT](https://hub.docker.com/r/ldes/ldi-workbench-nifi/tags)

**To Reproduce**
1. Follow the E2E test https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/demos/031.nifi-workbench-components
2. Start docker: ldes/ldi-workbench-nifi:1.9.0-SNAPSHOT
3. Login to Nifi https://localhost:8443/nifi/
4. Upload the file: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/demos/031.nifi-workbench-components/data/NiFi_Workbench_Components.json

**Current behavior**
Create version object processor is invalid.
![image](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/assets/15314807/a8bf8b08-a390-4cc6-b7fe-b860b14ae2c4)

**Comment by rorlic** [comment]
Test 031 is now fixed. In addition, this test is now automated as well.
