### ISSUE TITLE
 Cypress test 031-Error: Timed out waiting for container 'graphdb' to be available

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDES-E2E-testing#428]
**Prerequisites:**
E2E tests against Sprint 48 snapshots:
> [VSDS-LDESServer4J](https://hub.docker.com/r/ldes/ldes-server/tags) 
> 
> revision: [edd4232da9c5051bffc716e77f4c668d9f5e3488](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/edd4232da9c5051bffc716e77f4c668d9f5e3488)
> 
> tag: [ldes/ldes-server: 2.11.0-SNAPSHOT](https://hub.docker.com/r/ldes/ldes-server/tags)
> 
> [VSDS-Linked-Data-Interactions](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions)
> 
> revision:  [2a0c95075e095e51969756ff26b1062abbdf26b3](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/commit/2a0c95075e095e51969756ff26b1062abbdf26b3) 
> 
> [ldi-workbench-nifi](https://hub.docker.com/r/ldes/ldi-workbench-nifi/tags) tag: [ldes/ldi-workbench-nifi:2.2.0-SNAPSHOT](https://hub.docker.com/r/ldes/ldi-workbench-nifi/tags) 
> 
> [ldi-orchestrator](https://hub.docker.com/r/ldes/ldi-orchestrator/tags) tag: [ldes/ldi-orchestrator:2.2.0-SNAPSHOT](https://hub.docker.com/r/ldes/ldi-orchestrator/tags)

**Current result:**
test-031 failed: https://github.com/xdxxxdx/VSDS-LDES-E2E-testing/actions/runs/8360436381/job/22923959899#logs
with error:  Error: Timed out waiting for container 'graphdb' to be available

![image](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/assets/15314807/08f48268-0e5d-4c91-8cca-9e3cbb4cbc90)

I run one time the test manually, there is no issue detected.
But in the docker: (The issue may cause by it)
![image](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/assets/15314807/0a5fb5e0-d5a9-49d8-bd00-9bdf7793d79a)

**Comment by rorlic** [comment]
Test 031 has been completely re-written.
[Waiting for the graphDB to be available](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/b37384b268b2731d528ee080bc19ff6ed5361807/tests/031.nifi-workbench-components/docker-compose.yml#L168) seems to work fine now.
