### ISSUE TITLE
test-037: Error: Timed out waiting for container 'ldio-workbench' log to include 'LdesClientRunner setup finished'

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDES-E2E-testing#434]
Cypress auto run failed for Test-037, as https://github.com/xdxxxdx/VSDS-LDES-E2E-testing/actions/runs/8753683719
For Sprint 51.
If run this test locally, `docker compose up` failed to start the `provider` and `consumer` connectors with error: 
![image](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/assets/15314807/8e2cdef8-2e82-457c-afd3-f7846cc75792)
The configuration file https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/tests/037.dataspace-connector-http-code-and-headers/http-pull-provider/provider-configuration.properties need to be updated accordingly

**Comment by rorlic** [comment]
Test 037 now works correctly as we use a different method of wiating for the LDIO workbench to be available.
