### ISSUE TITLE
Invalid NIFI processors 2.7.0 - SNAPSHOTS

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDES-E2E-testing#438]
Following the instruction of https://informatievlaanderen.github.io/VSDS-Linked-Data-Interactions/ldi-nifi/index
Start nifi docker service with  2.7.0 - SNAPSHOTS https://s01.oss.sonatype.org/#nexus-search;quick~be.vlaanderen.informatievlaanderen.ldes.ldi.nifi
Upload the https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/tests/031.nifi-workbench-components/nifi-workflow.json to the NIFI.
There are few not valid processors:
![image](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/assets/15314807/d84472dc-e5f2-445c-b30a-80b50f2f451e)
![image](https://github.com/Informatievlaanderen/VSDS-Linked-Data-Interactions/assets/15314807/64e1c5bb-e4a5-414a-9f06-4f21d5799a93)

**Comment by xdxxxdx** [comment]
After discussed with @Yalz , the case is transferred to current repo as an enhancement. 
The E2E needs to be keep updated to the changes of Nifi component, as NIFI is still under supporting

**Comment by rorlic** [comment]
The [setup script for test 031](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/tests/031.nifi-workbench-components/setup.sh) now gets the latest available NiFi components and changes the workflow definition to use these.
