### ISSUE TITLE
Docker compose stop will not clean the enviroment

### ISSUE THREAD

**Issue by Krieke** [Informatievlaanderen/VSDS-LDES-E2E-testing#47]
https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/e2e-test/use-cases/gipod/4.time-fragment-ldes#restart-containers-between-the-scenarios explains that one should use `docker compose ... stop` to clean the environment. This is not correct. One will notice that the MongoDB still has the fragments after one restarts the environment again with `docker compose .. start`

I suggest the following changes:
- docker compose down  -v => the -v option will remove the volumes. the down will also remove the docker compose reference/tag to the docker containers, but will not remove the actual image on your system.
- docker compose up => can then be used to start things up again. If by any means the docker  image would have been removed they will be downloaded again. Another big asset is that the docker compose log console is by default enabled with this command. With the `docker compose ... start` one has to attach the log following again via `docker compose ... logs -f`

Note: the good thing with the above is that one has tested the mutability of the LDES members in the LDES fragment :-)

**Comment by zargha** [comment]
@rorlic This issue can be closed as the documentation has been updated with `docker compose <>  up` and `docker compose <> down`
