### ISSUE TITLE
Vulnerability: Dockerfiles

### ISSUE THREAD

**Issue by rorlic** [Informatievlaanderen/VSDS-LDES-E2E-testing#54]
Files: e2e-demo/template/ldes-client-workflow/Dockerfile, e2e-test/support/workflow/Dockerfile

Severity: HIGH

Description: Specify at least 1 USER command in Dockerfile with non-root user as argument. Running containers with 'root' user can lead to a container escape situation. It is a best practice to run containers as non-root users, which can be done by adding a 'USER' statement to the Dockerfile.

Link: https://avd.aquasec.com/misconfig/ds002

**Comment by rorlic** [comment]
The following also needs fixing:
![image](https://user-images.githubusercontent.com/501423/184099811-3d2528bc-3d0a-4eeb-b0e6-c92cccb7dc20.png)
![image](https://user-images.githubusercontent.com/501423/184099843-556c7091-1f2f-4508-a0c5-6aa8f4e6a282.png)

**Comment by rorlic** [comment]
The vulnerabilities in following files are IMHO false positives:
- e2e-demo/template/ldes-client-workflow/Dockerfile
- e2e-test/support/workflow/Dockerfile 

The USER command is used in the base image ([agturley/nifi](https://hub.docker.com/layers/nifi/agturley/nifi/1.16.3-jdk17/images/sha256-94b3fc65545ac2393f5c8848df287f39f1b094fc3331ed6c024034ad629e270c?context=explore)).
If I (temporary) append `ENTRYPOINT ["whoami"]` to the Docker file and rebuild and run a container, the result is user `nifi` displayed in the log file.

**Comment by Krieke** [comment]
@rorlic it is not because there is a user `nifi` that this is a user running without root privileges. The vulnerability reported here has to do with using the `USER` argument in the Dockerfile like described here: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user

**Comment by rorlic** [comment]
@Krieke I added a USER in the Docker.
